#!/bin/sh

# Copyright (c) 2000-2018, Board of Trustees of Leland Stanford Jr. University
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

VERSION=1.4.0-dev

_0=$(basename "${0}")
DEST="--global"

while true ; do

  case "${1}" in

    --help|-help|-h)
      cat <<EOF

${_0} [OPTIONS]

    --help, -h     Display this message and exit
    --version, -V  Display version and exit
    --local, -l    Use local Git settings instead of global

EOF
      exit 0
      ;;

    --local|-local|-l)
      DEST="--local"
      shift
      continue
      ;;

    --version|-version|-V|-v)
      echo "${_0} version ${VERSION}"
      exit 0
      ;;

  esac

  break
  
done

if [ "X${DEST}" = "X--local" ]; then
  if [ ! -d .git -o ! -f .git/config ]; then
    echo "${_0}: ${PWD} does not appear to be a Git repository" >&2
    exit 1
  fi
fi

if ! git flow version &> /dev/null ; then
  echo "${_0}: gitflow-avh or similar does not seem to be installed" >&2
  exit 1
fi 

echo "Setting up permanent branches..."
for k in master develop ; do
  git config $DEST "gitflow.branch.${k}" "${k}"
done

echo "Setting up branch prefixes and branch defaults..."
for k in feature release hotfix support bugfix ; do
  git config $DEST "gitflow.prefix.${k}" "${k}-"
  git config $DEST "gitflow.${k}.finish.keep" 'true'
  git config $DEST "gitflow.${k}.finish.squash" 'true'
done

echo "Setting up version tag prefix..."
git config $DEST 'gitflow.prefix.versiontag' 'version-'

#echo "Setting up hooks directory..."
#git config --local 'gitflow.path.hooks' "${PWD}/.git/hooks"

echo "Done."
